trigger:
  - master

pool:
  name: Default

steps:
  - script: echo "My Azure Pipeline "
    displayName: "Run a one-line script"

  - script: mvn clean install
    displayName: "Build with Maven"

  - script: java -jar target/MyMavenApp10-1.0-SNAPSHOT.jar
    displayName: "Running JAR"